# Generated by Django 3.2.4 on 2021-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_page', '0002_auto_20210610_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='chat_id',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
