# Generated by Django 3.2.4 on 2021-06-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_page', '0003_auto_20210610_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
